services:
  - type: web
    name: fastapi-service
    runtime: python
    buildCommand: cd fastapi_backend/  ||  pip install -r requirements.txt
    startCommand: uvicorn fastapi_backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

